stages:
  # - test
  # - build
  - deploy

deploy-release:
  stage: deploy
  tags:
    - dev-runner
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      - $CI_COMMIT_REF_NAME == "v2"
  image: registry.a-3.ru/frontend/base-images/node:16.13.0
  before_script:
    - export TAG=$(echo $CI_COMMIT_TAG | grep -E 'v[0-9]+.[0-9]+.[0-9]+' | sed -E -n 's/v([0-9]+.[0-9]+.[0-9]+)/\1/p')
    - export NODE_AUTH_TOKEN=$NPM_TOKEN
    - export NPM_REGISTRY=$NPM_PUBLISH_REGISTRY
    - npm run prepublishOnly-ci
  script:
    - npm config list
    - npm publish
