stages:
    - test
    - build
    - deploy

test-feature-on-push:
    stage: test
    tags:
        - dev-runner
    only:
        variables:
            - $CI_COMMIT_REF_NAME =~ /^(feature|fix)\/[a-zA-Z]+-?[0-9]+\/.+$/
    except:
        refs:
            - merge_requests
    image: registry.a-3.ru/frontend/base-images/node:12.13.1
    before_script:
        - yarn
        - yarn add react react-dom --peer
    script:
        - yarn test

test-feature-on-merge:
    stage: test
    tags:
        - dev-runner
    only:
        refs:
            - merge_requests
        variables:
            - $CI_COMMIT_REF_NAME =~ /^(feature|fix)\/[a-zA-Z]+-?[0-9]+\/.+$/
    image: registry.a-3.ru/frontend/base-images/node:12.13.1
    before_script:
        - yarn
        - yarn add react react-dom --peer
    script:
        - yarn test:coverage

test-release:
    stage: test
    tags:
        - dev-runner
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
            - $CI_COMMIT_REF_NAME == "master"
    image: registry.a-3.ru/frontend/base-images/node:12.13.1
    before_script:
        - yarn
        - yarn add react react-dom --peer
    script:
        - yarn test:coverage
    artifacts:
        paths:
            - node_modules
        expire_in: 10 min

build-release:
    stage: build
    tags:
        - dev-runner
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
            - $CI_COMMIT_REF_NAME == "master"
    image: registry.a-3.ru/frontend/base-images/node:12.13.1
    script:
        - yarn build
        - ls
    artifacts:
        paths:
            - dist
        expire_in: 10 min

deploy-release:
    stage: deploy
    tags:
        - dev-runner
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
            - $CI_COMMIT_REF_NAME == "master"
    image: registry.a-3.ru/frontend/base-images/node:12.13.1
    before_script:
        - export TAG=$(echo $CI_COMMIT_TAG | grep -E 'v[0-9]+.[0-9]+.[0-9]+' | sed -E -n 's/v([0-9]+.[0-9]+.[0-9]+)/\1/p')
        - ./bin/set_correct_version.sh
        - export NPM_REGISTRY=$NPM_PUBLISH_REGISTRY
        - ./bin/setup_local_npm.sh
    script:
        - npm publish --registry ${NPM_REGISTRY}
    dependencies:
        - build-release
