stages:
  - publish

publish:
  stage: publish
  tags:
    - dev-runner
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      - $CI_COMMIT_REF_NAME == "v2"
  image: registry.a-3.ru/frontend/base-images/node:16.13.0
  script:
    - node ./scripts/setupNpm.js
    - npm publish
